package:
  name: carculator_two_wheeler
  version: 0.1.1
source:
  path: ..
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"
requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.12,<3.13
    - carculator_utils >=1.3.6
test:
  imports:
    - carculator_two_wheeler
about:
  home: https://github.com/Laboratory-for-Energy-Systems-Analysis/carculator_two_wheeler
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Prospective life cycle assessment of two-wheelers
